import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const merriWeather = Merriweather({
  weight: ["300", "400", "700", "900"],
  style: ["italic", "normal"],
  subsets: ["latin"],
  display: "swap"
})

export const metadata: Metadata = {
  title: "Next Recipes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merriWeather.className} antialiased`}>
      <header>
        <NavBar />
      </header>
        <main className="bg-slate-900 min-h-screen p-6 text-white">
          {children}
        </main>
      </body>
    </html>
  );
}
