import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { ClerkProvider, SignInButton, SignUpButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import { ThemeSwitcher } from "@/components/ThemeSwitcher";

const merriWeather = Merriweather({
  weight: ["300", "400", "700", "900"],
  style: ["italic", "normal"],
  subsets: ["latin"],
  display: "swap"
})

export const metadata: Metadata = {
  title: "Next Recipes",
  description: "Generated by create next app",
};

export const darkAndLightMode = {
  darkMode: false,
  lightMode: false
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${merriWeather.className} antialiased`}>
        <header>
          <nav className="flex flex-row justify-between pr-20 bg-slate-800 text-white">
            <NavBar />
            <div className="flex flex-row gap-3">
              <ThemeSwitcher darkMode={darkAndLightMode.darkMode} lightMode={darkAndLightMode.lightMode}/>
              <SignedOut>
                <SignInButton />
                <SignUpButton />
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </nav>
        </header>
          <main className={`${darkAndLightMode.darkMode === true ? 'bg-slate-900 text-black' : ''} ${darkAndLightMode.lightMode === true ? 'bg-slate-50 text-white' : 'bg-slate-900 text-white'} min-h-screen p-6`}>
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
